### ISSUE TITLE
Meowri: working with code, Week 1

### ISSUE THREAD

**Issue by Meowri** [HackYourFutureBelgium/class-9-10#111]
- [x] :egg: [Group Intro Repo](https://github.com/Meowri/Let-it-be)
- [x] :egg: [Started my HYF Directory](https://github.com/Meowri?tab=following)
- [x] :egg: [_First Week on GitHub_](https://meowri.github.io/Master-of-none/.)
- [x] :egg: [My student bio](https://meowri.github.io/.)
- [x] :egg: [my `hack-my-future` repo](https://github.com/Meowri/hack-my-future)
- [x] :egg: my markdown home page: [Live](https://meowri.github.io/Let-it-be/), [Source](https://github.com/Meowri/Let-it-be)
- [x] :egg: [My _Learnables_ Project Board](https://github.com/users/Meowri/projects/1)

**Comment by mametur** [comment]
@Meowri I just have seen your label "help wanted" , where is not clear for you?

**Comment by mametur** [comment]
@Meowri I just  #saw your label   #111 "help wanted" , where is not clear for you?

**Comment by colevandersWands** [comment]
`master-of-none` :) nice!  Some tips on organizing files and folders:
* use numerals instead of words for numbers, and put the numbers at the beginning of the file name.  this way they'll all show up in order
* consider doing a folder for each module instead of a file per week.  then you can put more than just words as notes, you can add files of helpful code, images, ...
* so maybe: `/1-working-with-code`, `/2-incremental-development`, ...

And two things to fix:
* can you update the link to your learnables board?  this one still has `your-user-name`
* For your home page, you need to rename your repository to https://github.com/meowri/meowri.github.io.  You'll know you've got it right when this link works: https://meowri.github.io
* can you add a project board

**Comment by colevandersWands** [comment]
@Meowri , there's one more thing to fix that I missed the first time around.  You still need to make a pull request to the main class repo so that your student bio can be found from your "details" page: https://hackyourfuture.be/class-9-10/?student=Meowri
Right now your bio is only on your fork

**Comment by Meowri** [comment]
@mametur Thank you very much for reaching out, my apologies on not making clear what I need help on, in future, how should I specify where I am stuck on? I was stock on weather or not my homework was done correctly :) 
@colevandersWands Thank you so much for all the feedback, I think I have fixed all if it now? Could you kindly check again? Thank you

**Comment by colevandersWands** [comment]
@Meowri , still not quite.  The file name for you bio should be the same as your user name, this link should work: https://github.com/hackyourfuturebelgium/class-9-10/tree/master/student-bios/Meowri.md

**Comment by colevandersWands** [comment]
that link is still 404. You can change the name of your file directly from the class repo, no need for pull requesting

**Comment by Meowri** [comment]
Thank you Evan, I FINALLY figured out where to change the code! Could you kindly take a look once more, and confirm, this was a great "ah-ha" moment, so I really hope it is working now. Thank you for the patience, I inspected my bio link to finally figure it out.

**Comment by colevandersWands** [comment]
:octocat:  = 🐙 + 🐱
